[WIP] Enable "vela show" to support namespaced capability
oam-dev/kubevela pull request #1521
Opened 2021-04-17 15:12 UTC by zzxwill

Provide option `-namespace`, if not set, the default namespace
is default. If not found, as by default, capabilities are located in
vela-system, it will continue to retrieve the capability in
vela-system directory.

Fix #1520

2021-04-18 03:12 UTC, yangsoon commented
LGTM

2021-04-19 02:30 UTC, yangsoon commented on references/cli/show.go
> -			velaEnv, err := GetEnv(cmd)
We should get the namespace from `vela env` not from cli parameters

2021-04-19 02:34 UTC, wonderflow requested changes
the user story for `vela` is Appfile, which related with ENV for namespace.
And recently we have added `kubectl-vela` to tell the K8s oriented end user story, we can use `--namespace` there.

2021-04-19 02:44 UTC, zzxwill commented
@yangsoon @wonderflow Per the offline discussion, I will keep the `env` context. Thanks.

2021-04-19 16:01 UTC, zzxwill commented
@wonderflow @yangsoon Please help review it again. Thanks.

2021-04-20 03:01 UTC, yangsoon commented
LGTM

2021-04-20 04:49 UTC, wonderflow commented on references/plugins/cluster.go
> +	} else if kerrors.IsNotFound(err) && ns == types.DefaultNamespace {
```suggestion
	} else if kerrors.IsNotFound(err) {
```

2021-04-20 04:50 UTC, wonderflow commented on references/plugins/cluster.go
> +	} else if kerrors.IsNotFound(err) && ns == types.DefaultNamespace {
this check is no need

2021-04-20 04:50 UTC, wonderflow commented on references/plugins/cluster.go
> +	} else if kerrors.IsNotFound(err) && ns == types.DefaultNamespace {
```suggestion
	} else if kerrors.IsNotFound(err) {
```

2021-04-20 05:12 UTC, zzxwill commented on references/plugins/cluster.go
> +	} else if kerrors.IsNotFound(err) && ns == types.DefaultNamespace {
It's needed. If a user intended to switch environment by `vela env set`. We should search the definition from the namespace in the very environment, not in `vela-system`.

2021-04-20 05:16 UTC, zzxwill commented on references/plugins/cluster.go
> +	} else if kerrors.IsNotFound(err) && ns == types.DefaultNamespace {
另外，一个开发者只是想 vela show webservice，然后去写  application，如果我们不做这一步，他还要 1）去查 webservice 在哪个 namespace 下，2）知道 webservice 是根据 env 去过滤的。这两个条件对开发者都有门槛。

2021-04-20 08:34 UTC, wonderflow commented on references/plugins/cluster.go
> +	} else if kerrors.IsNotFound(err) && ns == types.DefaultNamespace {
没看懂你的代码和你解释的这个原因有什么关系。我理解你的代码的行为是：

```
如果在当前的 namespace下面没找到，并且当前的namespace是default namespace，才去vela-system namespace下去找。
```

我希望你改成：

```
如果在当前的 namespace下面没找到，就去 vela-system namespace下去找。
```

vela-system 是一个全局的 namespace。相当于 系统级别的能力。其他namespace的相当于用户自定义的能力。

2021-04-20 08:59 UTC, zzxwill commented on references/plugins/cluster.go
> +	} else if kerrors.IsNotFound(err) && ns == types.DefaultNamespace {
这样就没法满足用户就想去 env abc 下执行 vela show 的需求。

2021-04-20 09:09 UTC, wonderflow commented on references/plugins/cluster.go
> +	} else if kerrors.IsNotFound(err) && ns == types.DefaultNamespace {
用户在 env abc下面执行vela show，按照修改后的逻辑就是，先去  abc namespace下面查看，找不到就去 vela-system 查看。哪里不满足？

2021-04-20 12:39 UTC, zzxwill commented on references/plugins/cluster.go
> +	} else if kerrors.IsNotFound(err) && ns == types.DefaultNamespace {
我就想查 abc env 下的 webservice，没有就没有，预期是报错；但是你给我返回 vela-system 下面的，这个就给我错觉了，我以为 abc 下有且可用。

2021-04-20 13:35 UTC, wonderflow commented on references/plugins/cluster.go
> +	} else if kerrors.IsNotFound(err) && ns == types.DefaultNamespace {
> vela-system 是一个全局的 namespace。相当于 系统级别的能力。其他namespace的相当于用户自定义的能力。

This is our design.

2021-04-20 13:35 UTC, wonderflow commented on references/plugins/cluster.go
> +	} else if kerrors.IsNotFound(err) && ns == types.DefaultNamespace {
> 但是你给我返回 vela-system 下面的，这个就给我错觉了，我以为 abc 下有且可用。

另外，这个错觉有影响吗？

2021-04-21 05:59 UTC, wonderflow commented on apis/types/types.go
> +	DefaultNamespace = "default"
It's not used anywhere

2021-04-21 09:11 UTC, wonderflow approved these changes

2021-04-21 11:33 UTC, merged