add kubebuilder prerequisites in contributing.md
oam-dev/kubevela pull request #1675
Opened 2021-05-17 14:25 UTC by qingfengming

case offical doc only show v3 installation, add the v2 installation here.

[kubebuilder quick start, install](https://book.kubebuilder.io/quick-start.html#installation)

[discussion](https://github.com/oam-dev/kubevela/discussions/1672)

2021-05-17 14:54 UTC, captainroy-hy requested changes

2021-05-17 14:54 UTC, captainroy-hy commented on CONTRIBUTING.md
> +##### We also recommend you to learn about KubeVela's [design](https://kubevela.io/docs/concepts) before dive into its code.
```suggestion
We also recommend you to learn about KubeVela's [design](https://kubevela.io/docs/concepts) before diving into its code.
```

2021-05-17 14:54 UTC, captainroy-hy commented on CONTRIBUTING.md
> +sudo mv kubebuilder_2.3.1_darwin_amd64 /usr/local/kubebuilder
```suggestion
sudo mv kubebuilder_2.3.1_darwin_amd64/bin /usr/local/kubebuilder
```

2021-05-17 14:54 UTC, captainroy-hy commented on CONTRIBUTING.md
> +sudo mv kubebuilder_2.3.1_linux_amd64 /usr/local/kubebuilder
```suggestion
sudo mv kubebuilder_2.3.1_linux_amd64/bin /usr/local/kubebuilder
```

2021-05-17 14:54 UTC, captainroy-hy commented on CONTRIBUTING.md
> +
```suggestion
	 
</details>
```

2021-05-17 14:54 UTC, captainroy-hy commented on CONTRIBUTING.md
> +##### kubebuilder install:
```suggestion
<details>
  <summary>Install Kubebuilder manually</summary>
  
```

2021-05-17 14:54 UTC, captainroy-hy commented on CONTRIBUTING.md
> +##### kubebuilder install:
too much detail, let's put the code into a collapsed block to keep concise.

2021-05-17 14:54 UTC, captainroy-hy commented on CONTRIBUTING.md
> +5. kubebuilder v2.X.X
```suggestion
5. Kubebuilder v2.3.0+
```

2021-05-17 16:13 UTC, qingfengming commented on CONTRIBUTING.md
> +sudo mv kubebuilder_2.3.1_linux_amd64 /usr/local/kubebuilder
> 

i tested like this,  'make test' failed with "failed to start the controlplane. retried 5 times: fork/exec /usr/local/kubebuilder/bin/etcd: no such file or directory" .

2021-05-17 16:14 UTC, qingfengming commented on CONTRIBUTING.md
> +sudo mv kubebuilder_2.3.1_darwin_amd64 /usr/local/kubebuilder
same to above

2021-05-17 16:16 UTC, qingfengming commented on CONTRIBUTING.md
> +sudo mv kubebuilder_2.3.1_darwin_amd64 /usr/local/kubebuilder
Thank you very much!

2021-05-18 01:38 UTC, captainroy-hy commented on CONTRIBUTING.md
> +sudo mv kubebuilder_2.3.1_linux_amd64 /usr/local/kubebuilder
pls check it again. We need to move k8s control plane bins into `/usr/local/kubebuilder/bin`

2021-05-18 01:56 UTC, zzxwill commented on CONTRIBUTING.md
> +export PATH="/usr/local/kubebuilder/bin:$PATH"
Is exporting path necessary?

2021-05-18 01:57 UTC, zzxwill commented on CONTRIBUTING.md
> +We also recommend you to learn about KubeVela's [design](https://kubevela.io/docs/concepts) before diving into its code.
Let's keep a blank line before L42:)

2021-05-18 02:22 UTC, qingfengming commented on CONTRIBUTING.md
> +sudo mv kubebuilder_2.3.1_linux_amd64 /usr/local/kubebuilder
first, i run 'make test' success.

then, i test like this, and 'make test' failed again.
```
➜  kubevela cd /usr/local/kubebuilder
➜  kubebuilder cp -r bin/ ./
➜  kubebuilder ls
bin            etcd           kube-apiserver kubebuilder    kubectl
➜  kubebuilder ls bin
etcd           kube-apiserver kubebuilder    kubectl
➜  kubebuilder mv bin bin-back
➜  kubebuilder tree
.
├── bin-back
 │   ├── etcd
 │   ├── kube-apiserver
 │   ├── kubebuilder
 │   └── kubectl
├── etcd
├── kube-apiserver
├── kubebuilder
└── kubectl

 export PATH="/usr/local/kubebuilder:$PATH"
```

2021-05-18 02:28 UTC, captainroy-hy commented on CONTRIBUTING.md
> +sudo mv kubebuilder_2.3.1_linux_amd64 /usr/local/kubebuilder
your command will move the whole `kubebuilder_2.3.1_linux_amd64` dir, but we just need move `bin` dir, right?

2021-05-18 02:57 UTC, qingfengming commented on CONTRIBUTING.md
> +sudo mv kubebuilder_2.3.1_linux_amd64 /usr/local/kubebuilder
you mean create kubebuilder dir and mv  bin dir ? why not move and rename redirectly ?

2021-05-18 02:58 UTC, qingfengming commented on CONTRIBUTING.md
> +export PATH="/usr/local/kubebuilder/bin:$PATH"
no,but i think it's a part of installlation ?

2021-05-18 03:01 UTC, zzxwill commented on CONTRIBUTING.md
> +export PATH="/usr/local/kubebuilder/bin:$PATH"
Got it. Let's remove it as `kubebuilder` won't be directly called by users:)

2021-05-18 03:02 UTC, captainroy-hy commented on CONTRIBUTING.md
> +sudo mv kubebuilder_2.3.1_linux_amd64 /usr/local/kubebuilder
if users already have kubebuilder dir, this cmd will move dir into it instead of renaming.

2021-05-18 03:02 UTC, qingfengming commented on CONTRIBUTING.md
> +We also recommend you to learn about KubeVela's [design](https://kubevela.io/docs/concepts) before diving into its code.
ok

2021-05-18 03:13 UTC, qingfengming commented on CONTRIBUTING.md
> +export PATH="/usr/local/kubebuilder/bin:$PATH"
ok

2021-05-18 03:38 UTC, qingfengming commented on CONTRIBUTING.md
> +sudo mv kubebuilder_2.3.1_linux_amd64 /usr/local/kubebuilder
ok, thanks

2021-05-18 04:16 UTC, zzxwill approved these changes
Great!

2021-05-18 04:30 UTC, captainroy-hy approved these changes

2021-05-18 04:31 UTC, captainroy-hy commented
Good job!

2021-05-18 07:45 UTC, wonderflow commented
GOOD Job! and Job review !

2021-05-18 07:45 UTC, merged