end controller reconcile with conditions
oam-dev/kubevela pull request #1859
Opened 2021-06-29 14:39 UTC by captainroy-hy

Signed-off-by: roywang <seiwy2010@gmail.com>

**What this PR does / why we need it**:

Add util functions to handle ending reconciliation with conditions.

**Which issue(s) this PR fixes**:

Fixes #1188

**Special notes for your reviewer**:

2021-06-30 02:15 UTC, wonderflow commented on pkg/oam/util/helper.go
> +	ErrRecordedInCondition = "error is recorded in status condition, type: %q, msg: %q"
```suggestion
	ErrRecordedInCondition = "object level reconcile error, type: %q, msg: %q"
```

2021-07-02 09:32 UTC, wonderflow requested changes

2021-07-02 09:32 UTC, wonderflow commented on pkg/controller/core.oam.dev/v1alpha2/application/application_controller.go
> +	requeuedByUpdateSts bool
reconciler不能当handler那么用，会出现并发冲突

2021-07-02 09:32 UTC, wonderflow commented on pkg/controller/core.oam.dev/v1alpha2/application/application_controller.go
> +			r.requeuedByUpdateSts = true
我想了下，这个变量得包在 handler里面，UpdateStatus和 endWithNegativeCondition 也作为handler的成员函数，就能解决问题

2021-07-02 09:32 UTC, wonderflow commented on pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/applicationconfiguration.go
> +	return reconResult, nil
这里没看懂，跟原来逻辑为什么不一样了

2021-07-02 09:32 UTC, wonderflow commented on pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/applicationconfiguration.go
> +func (r *OAMApplicationReconciler) ACReconcile(ctx context.Context, ac *v1alpha2.ApplicationConfiguration) (result reconcile.Result, resultErr error) {
这里的改动也没看懂，不用setCondition的好处是？

2021-07-02 09:32 UTC, wonderflow commented on pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/applicationconfiguration_test.go
> +						// }),
这里不需要就删掉哈

2021-07-02 09:32 UTC, wonderflow commented on pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/revision_enable_test.go
> -		Expect(wr.GetGeneration()).Should(BeEquivalentTo(1))
这里为什么不用了？

2021-07-02 09:32 UTC, wonderflow commented on pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/revision_enable_test.go
> +			reconcileRetryAndExpectErr(reconciler, req)
这里的区别是？

2021-07-02 09:46 UTC, captainroy-hy commented on pkg/controller/core.oam.dev/v1alpha2/application/application_controller.go
> +			r.requeuedByUpdateSts = true
确实，我修改一下这块，不应该放在Reconciler里

2021-07-02 09:48 UTC, captainroy-hy commented on pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/applicationconfiguration.go
> +	return reconResult, nil
如果reconcile有了err，在前面EndReconcileWithNegativeCondition时就返回了；这一步就不需要返回任何error了

2021-07-02 09:51 UTC, captainroy-hy commented on pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/revision_enable_test.go
> +			reconcileRetryAndExpectErr(reconciler, req)
之前的实现里 reconcile的 err 都被吞掉了，永远不会返回error（除非最后的updateStatus出错）；修改之后是有可能抛出error的，而且这个error是用来触发requeue用的

2021-07-02 10:00 UTC, captainroy-hy commented on pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/applicationconfiguration.go
> +func (r *OAMApplicationReconciler) ACReconcile(ctx context.Context, ac *v1alpha2.ApplicationConfiguration) (result reconcile.Result, resultErr error) {
AppConfig只用了一种Condition，所以ACReconcile只要直接抛error，然后在Reconcile里做一次 SetCondition

2021-07-03 14:03 UTC, captainroy-hy commented on pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/revision_enable_test.go
> -		Expect(wr.GetGeneration()).Should(BeEquivalentTo(1))
和 line 1043-1044 重复了

2021-07-04 03:03 UTC, wonderflow commented on pkg/controller/core.oam.dev/v1alpha2/application/application_controller.go
> +			return res, nil
这里逻辑上有点问题：

1. 业务逻辑是rollout执行过程中需要进行入队，重新reconcile
2. update status本身其实有可能导致入队重新reconcile
3. endWithXXX 也会导致入队重新reconcile

这里我觉得可以简化。

1. 去掉 endWithNegativeCondition
2. 根据updateStatus是否真的update来判返回的 result还是否要重新入队

2021-07-04 03:08 UTC, wonderflow commented on pkg/controller/core.oam.dev/v1alpha2/application/apply.go
> +	if err := oamutil.EndReconcileWithNegativeCondition(ctx, h.r.Client, h.app, condition); err != nil && !h.requeuedByUpdateSts {
这里的逻辑我觉得可以调整成：

```
if h.requeuedByUpdateSts{
  return ctrl.Result{}, nil
}
if err := oamutil.EndReconcileWithNegativeCondition(ctx, h.r.Client, h.app, condition); err != nil  {
   return ctrl.Result{}, err
}


```

2021-07-04 03:09 UTC, wonderflow commented on pkg/controller/core.oam.dev/v1alpha2/application/apply.go
> +	if err := oamutil.EndReconcileWithNegativeCondition(ctx, h.r.Client, h.app, condition); err != nil && !h.requeuedByUpdateSts {
如果status已经被更新了，没必要更新 negativeCondition。 下次reconcile的时候如果有问题，还会触发，否则问题解了也没必要触发

2021-07-04 03:10 UTC, captainroy-hy commented on pkg/controller/core.oam.dev/v1alpha2/application/apply.go
> +	if err := oamutil.EndReconcileWithNegativeCondition(ctx, h.r.Client, h.app, condition); err != nil && !h.requeuedByUpdateSts {
这样会导致 condition 无法 patch

2021-07-04 03:11 UTC, captainroy-hy commented on pkg/controller/core.oam.dev/v1alpha2/application/application_controller.go
> +			return res, nil
endWithXXX在这里是给 updateSts出错时用的，假如update status出错了，需要借助endWithXXX 来保证重新入队

2021-07-04 03:16 UTC, wonderflow commented on pkg/controller/core.oam.dev/v1alpha2/application/apply.go
> +		if err = h.r.Get(ctx, client.ObjectKey{Namespace: h.app.Namespace, Name: h.app.Name}, h.app); err != nil {
这里不能用retry on conflict。

1. 我们的所有努力都是在避免出现 conflict，这里加个retry，掩盖了问题，也忽略了我们做出的努力。
2. 如果真的存在冲突，并且我们去 get 最新的app status，会出现以下问题：
  -  最新的 app status 可能是reconcile过新的一轮的，拿旧状态去更新会出现严重的错误
  - 重新获取的 status也无法保证它是老的状态，这里的deep equal 会产生歧义。

2021-07-04 03:17 UTC, wonderflow commented on pkg/controller/core.oam.dev/v1alpha2/application/apply.go
> +		stsBeforeUpdate := h.app.Status.DeepCopy()
这个 statusBefore 应该在application reconcile刚开始的时候去获取，而不是通过get

2021-07-04 03:17 UTC, wonderflow commented on pkg/controller/core.oam.dev/v1alpha2/application/apply.go
> +			return
PS. 这里的return没有返回参数，容易引起bug。

2021-07-04 03:21 UTC, wonderflow commented on pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/applicationconfiguration.go
> -		reconResult.RequeueAfter = 0
如果有error，这里 RequeueAfter 和 Requeue的参数都应该重置，这个逻辑重构后丢失了。

2021-07-04 03:23 UTC, wonderflow commented on pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/applicationconfiguration.go
> +func (r *OAMApplicationReconciler) ACReconcile(ctx context.Context, ac *v1alpha2.ApplicationConfiguration) (result reconcile.Result, resultErr error) {
这个是对的，那要再进一步判断一下，如果 EndReconcileWithNegativeCondition 已经更新了condition，updateStatus是否还需要？是不是当时updateStatus只是为了更新condition，还是说存在其他要更新的status？

2021-07-04 03:28 UTC, wonderflow commented on pkg/oam/util/helper.go
> +	}
这段判断逻辑有点奇怪，跟 crossplane 底层判重的逻辑一致吗？

2021-07-04 03:39 UTC, wonderflow commented on pkg/controller/core.oam.dev/v1alpha2/application/apply.go
> +// controller to requeue the object.
comment

2021-07-05 07:53 UTC, captainroy-hy commented on pkg/oam/util/helper.go
> +	}
嗯 是一致的，那个Equal方法就是crossplane的

2021-07-05 07:53 UTC, captainroy-hy commented on pkg/controller/core.oam.dev/v1alpha2/applicationconfiguration/applicationconfiguration.go
> -		reconResult.RequeueAfter = 0
fixed

2021-07-05 09:40 UTC, wonderflow commented on pkg/controller/core.oam.dev/v1alpha2/application/application_controller.go
> +	if endReconcile, err := r.handleFinalizers(ctx, app); endReconcile {
这里应该优先判断 err 不为 nil

2021-07-05 09:50 UTC, captainroy-hy commented on pkg/controller/core.oam.dev/v1alpha2/application/application_controller.go
> +	if endReconcile, err := r.handleFinalizers(ctx, app); endReconcile {
handleFinalizers 里的逻辑决定了 err!= nil 一定是伴随 endReconcile == true 返回的

2021-07-05 11:35 UTC, wonderflow commented on pkg/controller/core.oam.dev/v1alpha2/application/application_controller.go
> +	if endReconcile, err := r.handleFinalizers(ctx, app); endReconcile {
加个说明，这个逻辑比较hack

2021-07-05 11:42 UTC, wonderflow commented on pkg/controller/core.oam.dev/v1alpha2/core/workloads/containerizedworkload/containerizedworkload_controller.go
>  		return util.ReconcileWaitResult,
所有的 util.ReconcileWaitResult 都应该不需要了，因为如果error 发生就通过error入队了

2021-07-05 11:44 UTC, wonderflow commented on pkg/oam/util/helper.go
> +	}
这里的for循环先挑出当前类型的error，当前类型的error如果有多个呢？

2021-07-06 02:01 UTC, wonderflow commented on pkg/oam/util/helper.go
> +		existingCond := workload.GetCondition(newCond.Type)
// one condition type only matches one condition in the existing workload

2021-07-06 03:30 UTC, wonderflow commented on pkg/controller/core.oam.dev/v1alpha2/application/application_controller.go
> +	return ctrl.Result{}, errors.New("object level reconcile error")
error会在Controller日志中体现，这里要把error日志打印一下，不能输出无意义的错误。

2021-07-06 04:23 UTC, wonderflow approved these changes
good job

2021-07-06 05:54 UTC, merged