Migrate API Server code from velacp to this repo
oam-dev/kubevela pull request #2046
Opened 2021-08-07 08:10 UTC by hongchaodeng

The migration work includes:

- add `cmd/apiserver/` as a new binary
- add all apiserver code into `pkg/apiserver`
- merge go module + hack scripts
- add build steps in Makefile
- Dockerfile: add binary into kubevela docker container
- Chart: add a new apiserver container in the same pod as the controller, and expose a new service for it. In the values file, expose a new `apiserver` field for configuration.

2021-08-08 03:15 UTC, wonderflow commented on Dockerfile
> +    -o apiserver-${TARGETARCH} cmd/apiserver/main.go
let's write a new Dockerfile for it. Or please merge the code in the same main function.

2021-08-08 03:16 UTC, wonderflow commented on Dockerfile
> +    -o apiserver-${TARGETARCH} cmd/apiserver/main.go
写在一个main函数里共用binary ，如果要单独做个binary，就独立Dockerfile和镜像

2021-08-08 03:17 UTC, wonderflow commented on Makefile
> +		sha256sum vela/vela-* kubectl-vela/kubectl-vela-* apiserver/apiserver-* > sha256sums.txt \
这个apiserver单独编译和下载没必要，有docker image就好了。单独下载的都是CLI

2021-08-08 03:18 UTC, wonderflow commented on charts/vela-core/templates/kubevela-controller.yaml
> +        {{ end }}
单独搞个deployment 放这个镜像更好一些

2021-08-08 03:21 UTC, wonderflow commented on cmd/apiserver/main.go
> +	)
还会有别的command加进来吗

2021-08-08 03:24 UTC, wonderflow commented on go.mod
> +	github.com/labstack/echo/v4 v4.5.0
我们之前用的是 gin（L26 行引入了 github.com/gin-gonic/gin），这里又引入echo，所以有2个web框架，不统一了。

需要回答：

1. 选echo不用gin的原因？
2. 原来的gin是不是可以替换成echo？

2021-08-08 03:26 UTC, wonderflow commented on pkg/apiserver/common/cue.go
> +}
这里出现了很多新的cue代码，原来kubevela 库里应该都有的吧？ \cc @leejanee

2021-08-08 03:28 UTC, wonderflow commented on pkg/apiserver/proto/model/application.proto
> +}
这个application的模型跟 KubeVela Go 的结构体差异很大，而且很难维护，我觉得应该趁这个机会改掉。

我们引入pb带来了额外的维护成本，有什么收益吗？

2021-08-08 03:29 UTC, wonderflow commented on pkg/apiserver/proto/model/capability.proto
> +}
这个capabilities同样跟X-Definition 有很大的差异

2021-08-08 03:30 UTC, wonderflow commented on pkg/apiserver/rest/client/initClient.go
> +}
有同样函数了，应该是在 common 之类的包里

2021-08-08 03:32 UTC, wonderflow commented on pkg/apiserver/rest/services/application.go
> +	cli, err := s.getClientByClusterName(clusterName)
多集群应该是kubevela 控制器层面解决的，这个逻辑不应该在apiserver

2021-08-08 03:37 UTC, wonderflow requested changes
整体问题比较多：

1. pb和go struct的转换，我看到了很多额外的decode和encode，不光是性能影响，字段也不一致，信息损失。
2. 这里的apiserver关系？ https://github.com/oam-dev/kubevela/tree/master/references/apiserver 需要清理和一致化。
3. 没有任何测试和CI。

2021-08-08 03:42 UTC, hongchaodeng commented on Dockerfile
> +    -o apiserver-${TARGETARCH} cmd/apiserver/main.go
单独写一个 Dockerfile 没问题。但是在开源我们并不打算也不应该单独做一个镜像。这样会造成额外的分发负担。

2021-08-08 03:43 UTC, hongchaodeng commented on charts/vela-core/templates/kubevela-controller.yaml
> +        {{ end }}
有这个必要吗？

2021-08-08 03:44 UTC, hongchaodeng commented on cmd/apiserver/main.go
> +	)
有可能。

2021-08-08 03:45 UTC, hongchaodeng commented on go.mod
> +	github.com/labstack/echo/v4 v4.5.0
> 我们之前用的是 gin

并没有。

> L26 行引入了 github.com/gin-gonic/gin

这个依赖不知道哪里来的。接下里试着删掉。

2021-08-08 03:46 UTC, hongchaodeng commented on pkg/apiserver/common/cue.go
> +}
apiserver 肯定有一些代码会跟主库 share，这也是迁移进来的目的之一。
但是这个 PR 不会做这样的 merge 改动。需要合并的地方请先开新的 issue 来记录。

2021-08-08 03:47 UTC, hongchaodeng commented on pkg/apiserver/proto/model/application.proto
> +}
apiserver 肯定有一些代码会跟主库 share，这也是迁移进来的目的之一。
但是这个 PR 不会做这样的 merge 改动。需要合并的地方请先开新的 issue 来记录。

2021-08-08 03:47 UTC, hongchaodeng commented on pkg/apiserver/proto/model/capability.proto
> +}
apiserver 肯定有一些代码会跟主库 share，这也是迁移进来的目的之一。
但是这个 PR 不会做这样的 merge 改动。需要合并的地方请先开新的 issue 来记录。

2021-08-08 03:47 UTC, hongchaodeng commented on pkg/apiserver/rest/client/initClient.go
> +}
apiserver 肯定有一些代码会跟主库 share，这也是迁移进来的目的之一。
但是这个 PR 不会做这样的 merge 改动。需要合并的地方请先开新的 issue 来记录。

2021-08-08 03:47 UTC, hongchaodeng commented on pkg/apiserver/rest/services/application.go
> +	cli, err := s.getClientByClusterName(clusterName)
apiserver 肯定有一些代码会跟主库 share，这也是迁移进来的目的之一。
但是这个 PR 不会做这样的 merge 改动。需要合并的地方请先开新的 issue 来记录。

2021-08-08 03:49 UTC, hongchaodeng commented
> pb和go struct的转换，我看到了很多额外的decode和encode，不光是性能影响，字段也不一致，信息损失。

对于 pb vs go struct 的改动我理解。但是这次改动只做迁移，不做额外开发。这些问题请先开 issue 记录。

> 这里的apiserver关系？ https://github.com/oam-dev/kubevela/tree/master/references/apiserver 需要清理和一致化。

原来的 apiserver 已经没人维护了。需要删除掉。但是这次改动只做迁移，不做额外开发。这些问题请先开 issue 记录。

> 没有任何测试和CI。

行。这个马上加上。

2021-08-08 03:50 UTC, hongchaodeng commented on Makefile
> +		sha256sum vela/vela-* kubectl-vela/kubectl-vela-* apiserver/apiserver-* > sha256sums.txt \
好的。应该删掉。

2021-08-10 02:26 UTC, hongchaodeng commented
按照最新的讨论改动完毕：


- [X] model 层从 pb 改成了 go struct
- [X] 添加了 unit test (其实是 integration test) 并作为标准案例。
- [X] CI 里面 Cover 住测试
- [X] cmd 去掉了 sub-command

2021-08-10 05:23 UTC, wonderflow commented on pkg/utils/k8sutil/client.go
> +}
放到这个文件，跟里面的函数做一下合并吧  `pkg/utils/common/common.go`

2021-08-10 05:24 UTC, wonderflow approved these changes
please fix CI

2021-08-10 06:13 UTC, wangyuan249 commented on pkg/utils/k8sutil/client.go
> +}
ok , I will follow up this task

2021-08-10 06:13 UTC, wangyuan249 commented on pkg/utils/k8sutil/client.go
> +}
include CI

2021-08-11 15:37 UTC, hongchaodeng commented
The e2e is unstable due to downloading kruise chart:
```
helm install kruise https://github.com/openkruise/kruise/releases/download/v0.7.0/kruise-chart.tgz
Error: failed to download "https://github.com/openkruise/kruise/releases/download/v0.7.0/kruise-chart.tgz" (hint: running `helm repo update` may help)
make: *** [Makefile:150: e2e-setup] Error 1
```

Will retry tomorrow

2021-08-12 02:57 UTC, yangsoon commented
> The e2e rollout test is unstable due to downloading kruise chart:
> 
> ```
> helm install kruise https://github.com/openkruise/kruise/releases/download/v0.7.0/kruise-chart.tgz
> Error: failed to download "https://github.com/openkruise/kruise/releases/download/v0.7.0/kruise-chart.tgz" (hint: running `helm repo update` may help)
> make: *** [Makefile:150: e2e-setup] Error 1
> ```
> 
> Will retry tomorrow

sorry, I have fix this problem. please try again.

2021-08-12 03:13 UTC, merged