Fix: Align -n command argument
oam-dev/kubevela pull request #2719
Opened 2021-11-15 12:55 UTC by chivalryq

### Description of your changes

Align commands to use `-n` means namespace

Fixes #

I have:

- [ ] Read and followed KubeVela's [contribution process](https://github.com/oam-dev/kubevela/blob/master/contribute/create-pull-request.md).
- [ ] [Related Docs](https://github.com/oam-dev/kubevela.io) updated properly. In a new feature or configuration option, an update to the documentation is necessary. 
- [ ] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### How has this code been tested

### Special notes for your reviewer

2021-11-16 03:47 UTC, Somefive approved these changes
lgtm

2021-11-16 05:46 UTC, wonderflow commented on references/cli/def.go
> -	FlagInteractive = "interactive"
why they're deleted?

2021-11-16 05:48 UTC, wonderflow commented on references/appfile/api/appfile.go
> -func (app *AppFile) BuildOAMApplication(env *types.EnvMeta, io cmdutil.IOStreams, tm template.Manager, silence bool) (*v1beta1.Application, []oam.Object, error) {
we should keep the env concept and add `namespace` args as override. Keep the compatibility

2021-11-16 14:27 UTC, chivalryq commented on references/appfile/api/appfile.go
> -func (app *AppFile) BuildOAMApplication(env *types.EnvMeta, io cmdutil.IOStreams, tm template.Manager, silence bool) (*v1beta1.Application, []oam.Object, error) {
I think we shouldn't keep env concept any more. There are three reasons 
1. It's originally for create namespace. If we keep 2 concept, users will be confused.
2. As we all focus on release 1.2 now. There are already a lot concepts about envrionment. We shouldn't keep this as another environment.
3. It's easy to swtch from -e to -n.

2021-11-16 14:52 UTC, wonderflow commented on references/appfile/api/appfile.go
> -func (app *AppFile) BuildOAMApplication(env *types.EnvMeta, io cmdutil.IOStreams, tm template.Manager, silence bool) (*v1beta1.Application, []oam.Object, error) {
如果要删就要整体都删，不能半吊子

2021-11-17 02:22 UTC, chivalryq commented on references/appfile/api/appfile.go
> -func (app *AppFile) BuildOAMApplication(env *types.EnvMeta, io cmdutil.IOStreams, tm template.Manager, silence bool) (*v1beta1.Application, []oam.Object, error) {
我遗留的部分是exec/port-forward/logs，在 @Somefive 的工作流程中，他合并后我会继续把这个概念清理干净

2021-11-17 07:14 UTC, wonderflow commented on references/appfile/api/appfile.go
> -func (app *AppFile) BuildOAMApplication(env *types.EnvMeta, io cmdutil.IOStreams, tm template.Manager, silence bool) (*v1beta1.Application, []oam.Object, error) {
那先把 vela env 命令清理掉

2021-11-17 07:17 UTC, wonderflow requested changes
we should keep the compatibility with `vela env` until we have alternative plan

2021-11-17 08:32 UTC, wonderflow approved these changes
good job

2021-11-19 10:00 UTC, merged