Add addon arguments API
oam-dev/kubevela pull request #2732
Opened 2021-11-17 11:03 UTC by chivalryq

### Description of your changes

Fixes #

I have:

- [ ] Read and followed KubeVela's [contribution process](https://github.com/oam-dev/kubevela/blob/master/contribute/create-pull-request.md).
- [ ] [Related Docs](https://github.com/oam-dev/kubevela.io) updated properly. In a new feature or configuration option, an update to the documentation is necessary. 
- [ ] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### How has this code been tested

### Special notes for your reviewer

2021-11-17 11:04 UTC, hongchaodeng approved these changes

2021-11-17 11:13 UTC, zzxwill commented
What does `status` mean? Is `example` the name of an add-on?

2021-11-17 11:20 UTC, barnettZQG commented on pkg/apiserver/rest/usecase/addon.go
> +		err := u.kubeClient.Get(ctx, client.ObjectKey{
参数应该在任何状态下都应该返回。

2021-11-17 11:20 UTC, barnettZQG commented on pkg/apiserver/rest/usecase/addon.go
> +		sec := pkgaddon.RenderArgsSecret(addon, args.Args)
如果需要存储 addon 配置数据，应该使用DB。

2021-11-17 11:38 UTC, chivalryq commented on pkg/apiserver/rest/usecase/addon.go
> +		err := u.kubeClient.Get(ctx, client.ObjectKey{
这里返回的参数是enable的参数，在未enable的情况下返回null

2021-11-17 11:41 UTC, chivalryq commented on pkg/apiserver/rest/usecase/addon.go
> +		sec := pkgaddon.RenderArgsSecret(addon, args.Args)
我认为这个实现区别不大，请说明使用db的优势

2021-11-17 11:42 UTC, chivalryq commented
> What does `status` mean? Is `example` the name of an add-on?

/addons/{name}/status will return addon's status(is enabled or not) and it's enable argument.

2021-11-17 11:59 UTC, barnettZQG commented on pkg/apiserver/rest/usecase/addon.go
> +		sec := pkgaddon.RenderArgsSecret(addon, args.Args)
统一存储哈，API层元数据全部进DB

2021-11-17 12:01 UTC, barnettZQG commented on pkg/apiserver/rest/usecase/addon.go
> +		err := u.kubeClient.Get(ctx, client.ObjectKey{
用户有没有配置参数与你应用的状态没有绝对关联性。举个例子：

用户配置数据错误，发起enable，这时候Application创建不出来。此时用户依然需要能够在原来配置参数基础上修改。

2021-11-17 12:45 UTC, chivalryq commented on pkg/apiserver/rest/usecase/addon.go
> +		err := u.kubeClient.Get(ctx, client.ObjectKey{
用户看到了addon未启用，却看到了参数，这种情况不应该出现。参数应当和状态是相关的。

2021-11-17 12:52 UTC, zzxwill commented
> > What does `status` mean? Is `example` the name of an add-on?
> 
> /addons/{name}/status will return addon's status(is enabled or not) and its enable argument if enabled

对于 terraform，里边的 ak/sk 这些有忽略吗？这些不能直接返回。

2021-11-17 12:52 UTC, chivalryq commented on pkg/apiserver/rest/usecase/addon.go
> +		err := u.kubeClient.Get(ctx, client.ObjectKey{
你想表达的配置错误，应该是在enable中发生错误，这种时候不应该刷新表单，而不是数据落库再读出来给用户。

2021-11-17 12:59 UTC, zzxwill commented
> > > What does `status` mean? Is `example` the name of an add-on?
> > 
> > 
> > /addons/{name}/status will return addon's status(is enabled or not) and its enable argument if enabled
> 
> 对于 terraform，里边的 ak/sk 这些有忽略吗？这些不能直接返回。

可以把参数做一下标记，Terraform outputs 不能显示输出的方案，供参考：
https://www.terraform.io/docs/language/values/outputs.html#sensitive-suppressing-values-in-cli-output

2021-11-17 13:18 UTC, chivalryq commented
我们应该给 parameter.cue 中的字段加一个标记方法，标记该参数为敏感参数，应该在输入时渲染为密码类型，输出时打码处理。

2021-11-18 03:05 UTC, zzxwill requested changes
Please give an actual example to get the details of addon observability and terraform, terrafom-provider-alicloud. /cc @wonderflow

2021-11-18 04:23 UTC, hongchaodeng approved these changes

2021-11-18 04:24 UTC, merged