Fix: install Terraform and apply the support for a provider in one jump
oam-dev/kubevela pull request #2778
Opened 2021-11-23 06:21 UTC by zzxwill

- Fix issue: addon name should not include forward-slash "/" cloud-resource fix addon name should not include forward-slash "/" #2588
- Install terraform and the provider in one jump. Instead of installing terraform
and terraform-xxx in two steps
- Terraform ComponenetDefinition won't be applied at once even though not all of them are needed

Commit again after https://github.com/oam-dev/kubevela/pull/2773 is reverted.

### Description of your changes

Fixes #

I have:

- [ ] Read and followed KubeVela's [contribution process](https://github.com/oam-dev/kubevela/blob/master/contribute/create-pull-request.md).
- [ ] [Related Docs](https://github.com/oam-dev/kubevela.io) updated properly. In a new feature or configuration option, an update to the documentation is necessary. 
- [ ] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### How has this code been tested

### Special notes for your reviewer

2021-11-24 07:51 UTC, hongchaodeng approved these changes

2021-11-24 12:42 UTC, Somefive approved these changes

2021-11-26 09:14 UTC, chivalryq requested changes

2021-11-26 12:51 UTC, zzxwill commented on references/cli/addon.go
> -		"terraform-provider/azure":   "default",
Fixed.

2021-11-26 14:38 UTC, hongchaodeng approved these changes

2021-11-26 15:01 UTC, merged