Fix: #2799
oam-dev/kubevela pull request #2800
Opened 2021-11-24 13:20 UTC by barnettZQG

2021-11-24 15:40 UTC, hongchaodeng approved these changes

2021-11-25 06:44 UTC, wonderflow requested changes
please modify your PR title and commit message

2021-11-29 05:26 UTC, wonderflow approved these changes

2021-12-01 02:28 UTC, yangsoon approved these changes

2021-12-03 09:12 UTC, closed without merging