Feat: add addon invisible field
oam-dev/kubevela pull request #2820
Opened 2021-11-26 09:05 UTC by chivalryq

### Description of your changes

Add addon `invisible` filed in addon's metadata. This will perform like:
1. "invisible: true" means addon won't be listed.
2. When an addon is enabled, check its dependent addon.
  - invisible addon will be enabled automatically.
  - common addon will block the enable process

Fixes #

I have:

- [x] Read and followed KubeVela's [contribution process](https://github.com/oam-dev/kubevela/blob/master/contribute/create-pull-request.md).
- [ ] [Related Docs](https://github.com/oam-dev/kubevela.io) updated properly. In a new feature or configuration option, an update to the documentation is necessary. 
- [ ] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### How has this code been tested

### Special notes for your reviewer

2021-11-26 09:55 UTC, zzxwill requested changes
LGTM!

To make addon invisible, the definitions of Terraform should not change.

2021-11-26 11:54 UTC, hongchaodeng approved these changes

2021-11-26 15:11 UTC, zzxwill approved these changes

2021-11-27 03:40 UTC, yangsoon approved these changes

2021-11-27 04:09 UTC, Somefive approved these changes

2021-11-27 05:06 UTC, merged