Feat: userInfoCollection logic in apiserver
oam-dev/kubevela pull request #3082
Opened 2022-01-12 08:09 UTC by wangyikewxgm

Signed-off-by: wangyike <wangyike_wyk@163.com>

1. `get` userInfoCollection will return

```json
{
    "userID": "n9qpmg2wtkcbj4cc",
    "enableCollection": true
}
```
 
first `get` request will generate a UserID by random

2. post request `enable/disable`  will enable or disable user-Info-collection
3. write e2e-test

### Description of your changes

Fixes #

I have:

- [ ] Read and followed KubeVela's [contribution process](https://github.com/oam-dev/kubevela/blob/master/contribute/create-pull-request.md).
- [ ] [Related Docs](https://github.com/oam-dev/kubevela.io) updated properly. In a new feature or configuration option, an update to the documentation is necessary. 
- [ ] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### How has this code been tested

### Special notes for your reviewer

2022-01-12 09:44 UTC, wonderflow commented on pkg/apiserver/model/user_info_collection.go
> +type UserInfoCollection struct {
```suggestion
type SystemInfoCollection struct {
```

2022-01-12 09:44 UTC, wonderflow commented on pkg/apiserver/model/user_info_collection.go
> +	UserID           string `json:"userID"`
InstallID

2022-01-12 09:44 UTC, wonderflow requested changes
rename overall

2022-01-12 10:58 UTC, barnettZQG commented on pkg/apiserver/model/user_info_collection.go
> +type UserInfoCollection struct {
SystemInfo

2022-01-12 11:16 UTC, wangyikewxgm commented on pkg/apiserver/model/user_info_collection.go
> +type UserInfoCollection struct {
fixed

2022-01-13 02:37 UTC, wonderflow approved these changes

2022-01-13 02:51 UTC, barnettZQG commented on pkg/apiserver/rest/webservice/system_info.go
> +	ws.Route(ws.POST("/enable").To(u.enableSystemInfo).
The enable and disable API are not needed. Just provide an Update API for updating all system info.

2022-01-13 02:57 UTC, barnettZQG commented
Don't have an API to get system version and statistics about app、cluster and addon?

2022-01-13 03:43 UTC, wangyikewxgm commented on pkg/apiserver/rest/webservice/system_info.go
> +	ws.Route(ws.POST("/enable").To(u.enableSystemInfo).
考虑过这种情况，但我觉的接口这种设计是合理的。因为第一次Get请求回创建一个installID有一种情况是在系统引导阶段用户需要直接disable掉collection，现在这种接口设计也是能够支持的。用过是update接口的话，你需要传一个installID，但这个时候还没有生成这个Id。

2022-01-13 03:46 UTC, wangyikewxgm commented
> Don't have an API to get system version and statistics about app、cluster and addon?

We have discuss this problem offline, do  we. The dashboard can get these info from other apiserver interface. There is no need add other interface to return them.

2022-01-13 03:55 UTC, wangyikewxgm commented on pkg/apiserver/rest/webservice/system_info.go
> +	// Get
fixed

2022-01-13 05:43 UTC, barnettZQG commented
> We have discuss this problem offline, do we?The dashboard can get these info from other apiserver interface. There is no need add other interface to return them.

There is no version info.

2022-01-13 05:46 UTC, barnettZQG commented on pkg/apiserver/rest/webservice/system_info.go
> +	ws.Route(ws.POST("/enable").To(u.enableSystemInfo).
SystemInfo 这个表以后是作为系统设置参数的存储，目前只有一个参数 “禁止数据收集”。

2022-01-13 05:56 UTC, wangyikewxgm commented on pkg/apiserver/rest/webservice/system_info.go
> +	ws.Route(ws.POST("/enable").To(u.enableSystemInfo).
version 是可以存在这个表当中，但这个值不应该由用户通过接口去修改才对吧

2022-01-13 06:01 UTC, barnettZQG commented on pkg/apiserver/rest/webservice/system_info.go
> +	ws.Route(ws.POST("/enable").To(u.enableSystemInfo).
版本不需要存储，直接读取，接口返回。

2022-01-13 06:11 UTC, wangyikewxgm commented on pkg/apiserver/rest/webservice/system_info.go
> +	ws.Route(ws.POST("/enable").To(u.enableSystemInfo).
> 版本不需要存储，直接读取，接口返回。

对，我也想到这个了，那就接口就保持这个样子吧， 只保留enable/disable 因为用户只能修改是否收集。但系统信息接口回返回version 数据。

2022-01-13 06:27 UTC, barnettZQG commented on pkg/apiserver/rest/webservice/system_info.go
> +	ws.Route(ws.POST("/enable").To(u.enableSystemInfo).
这个接口完全不符合寓意，建议直接变更为 PUT 接口哈。 SystemInfo 只会有一条数据，不需要用 installID 进行什么塞选哈。

2022-01-13 06:38 UTC, wangyikewxgm commented on pkg/apiserver/rest/webservice/system_info.go
> +	ws.Route(ws.POST("/enable").To(u.enableSystemInfo).
Put 请求body里传一整个systemInfo struct ，但只有enableCollection 字段会会生效？

2022-01-13 06:51 UTC, barnettZQG commented on pkg/apiserver/rest/webservice/system_info.go
> +	ws.Route(ws.POST("/enable").To(u.enableSystemInfo).
{
  enableCollection: bool
}

2022-01-13 11:48 UTC, wangyikewxgm commented on pkg/apiserver/rest/webservice/system_info.go
> +	ws.Route(ws.POST("/enable").To(u.enableSystemInfo).
fixed

2022-01-13 11:59 UTC, wangyikewxgm commented
> > We have discuss this problem offline, do we?The dashboard can get these info from other apiserver interface. There is no need add other interface to return them.
> 
> There is no version info.

Added version info.

2022-01-14 02:15 UTC, barnettZQG approved these changes

2022-01-14 02:16 UTC, merged