Fix: Let versioned  controller uses a separate election locker in one cluster.
oam-dev/kubevela pull request #3298
Opened 2022-02-18 09:15 UTC by leejanee

Signed-off-by: Jian.Li <lj176172@alibaba-inc.com>

### Description of your changes

Fixes #

 Let versioned  controller uses a separate election locker in one cluster.
I have:

- [ ] Read and followed KubeVela's [contribution process](https://github.com/oam-dev/kubevela/blob/master/contribute/create-pull-request.md).
- [ ] [Related Docs](https://github.com/oam-dev/kubevela.io) updated properly. In a new feature or configuration option, an update to the documentation is necessary. 
- [ ] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### How has this code been tested

### Special notes for your reviewer

2022-02-18 09:20 UTC, hongchaodeng approved these changes

2022-02-18 09:21 UTC, wonderflow commented on pkg/utils/util/factory.go
> +	return name + "-" + strings.ToLower(strings.ReplaceAll(version.VelaVersion, ".", "z"))
```suggestion
	return name + "-" + strings.ToLower(strings.ReplaceAll(version.VelaVersion, ".", "-"))
```

2022-02-18 09:21 UTC, wonderflow commented on pkg/utils/util/factory_test.go
> +		t.Errorf("id is not as expected(%s != kubevela-v10z13z0)", id)
```suggestion
		t.Errorf("id is not as expected(%s != kubevela-v10-13-0)", id)
```

2022-02-18 09:21 UTC, wonderflow commented on pkg/utils/util/factory.go
> +
format

2022-02-18 09:22 UTC, wonderflow commented on cmd/core/main.go
> +
format

2022-02-18 09:23 UTC, wonderflow commented on pkg/utils/util/factory.go
> +	return name + "-" + strings.ToLower(strings.ReplaceAll(version.VelaVersion, ".", "z"))
```
if versionedDeploy{
  return name+"-"+...
}
return name

```

2022-02-18 09:23 UTC, wonderflow commented on pkg/utils/util/factory_test.go
> +	if id := GenerateLeaderElectionID("kubevela", true); id != "kubevela-v10z13z0" {
add a test about false case

2022-02-18 09:25 UTC, wonderflow requested changes
please make sure it's compatible

2022-02-21 09:07 UTC, wonderflow approved these changes

2022-02-21 11:54 UTC, merged