Fix: addon store&show complicated parameter
oam-dev/kubevela pull request #3310
Opened 2022-02-22 12:11 UTC by wangyikewxgm

fix complicate args storage

Signed-off-by: 楚岳 <wangyike.wyk@alibaba-inc.com>

### Description of your changes

Fixes #

I have:

- [ ] Read and followed KubeVela's [contribution process](https://github.com/oam-dev/kubevela/blob/master/contribute/create-pull-request.md).
- [ ] [Related Docs](https://github.com/oam-dev/kubevela.io) updated properly. In a new feature or configuration option, an update to the documentation is necessary. 
- [ ] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### How has this code been tested

### Special notes for your reviewer

2022-02-22 12:34 UTC, barnettZQG approved these changes
LGTM

2022-02-23 03:21 UTC, wonderflow requested changes
please addon test case to indicate the error

2022-02-23 04:25 UTC, wangyikewxgm commented
> please addon test case to indicate the error

added

2022-02-23 05:34 UTC, wonderflow approved these changes

2022-02-23 06:35 UTC, merged