Feat: add pod only param in vela-core chart
oam-dev/kubevela pull request #3476
Opened 2022-03-21 02:26 UTC by chivalryq

Signed-off-by: qiaozp <chivalry.pp@gmail.com>

### Description of your changes

Now our Helm chart contains several Deployment/Job manifests. We want to use vela-core's multicluster in ACK One mode, which means install the chart in a cluster whose controller-manager is incomplete.

This PR provide a parameter: podOnly in vela-core chart. It won't affect the default install behavior. When set podOnly=true. All Deployments will be replaced with Pod with the same spec.

Here is the replaced manifest list :

- kubevela-controller
- cluster-gateway
- kubevela-vela-core-admission-create
- kubevela-vela-core-admission-patch

Fixes #

I have:

- [x] Read and followed KubeVela's [contribution process](https://github.com/oam-dev/kubevela/blob/master/contribute/create-pull-request.md).
- [ ] [Related Docs](https://github.com/oam-dev/kubevela.io) updated properly. In a new feature or configuration option, an update to the documentation is necessary. 
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### How has this code been tested

### Special notes for your reviewer

2022-03-21 02:34 UTC, Somefive approved these changes

2022-03-21 02:36 UTC, wonderflow requested changes
This change will make the chart hardly to maintain. Is there any alternative solution?

I think we can create a pod spec yaml and use the same values.yaml?

2022-03-21 03:16 UTC, chivalryq commented
>

2022-03-21 03:16 UTC, chivalryq commented
> This change will make the chart hardly to maintain. Is there any alternative solution?

> I think we can create a pod spec yaml and use the same values.yaml?

Do you mean helm chart is like below?

```
#deploy.yaml
{{ if not podOnly }}
Deployment
{{ end }}

# pod.yaml
{{ if .Values.PodOnly }}
Pod
{{ end }}
```

This creates a duplicate copy.

2022-03-23 07:22 UTC, chivalryq commented
ping @wonderflow please review again.

2022-03-24 01:52 UTC, wonderflow commented
let's move this feature into a seprate project https://github.com/oam-dev/velad

2022-03-28 09:05 UTC, wonderflow commented on charts/vela-core/values.yaml
> +podOnly: false
```suggestion
deployByPod: false
```

2022-04-05 15:12 UTC, closed without merging