Feat: enhance storage trait to support multi-mountToEnv config
oam-dev/kubevela pull request #3546
Opened 2022-03-29 10:40 UTC by ZhongsJie96

Signed-off-by: Shijie Zhong <zhongsjie@cmbchina.com>

### Description of your changes
Support the multi-mountToEnv parameter of storage trait in secret and configmap. By this feature, we can mount multi-env in container env, without creating multi-secreat or multi-configmap resrouces

I have:

- [ ] Read and followed KubeVela's [contribution process](https://github.com/oam-dev/kubevela/blob/master/contribute/create-pull-request.md).
- [ ] [Related Docs](https://github.com/oam-dev/kubevela.io) updated properly. In a new feature or configuration option, an update to the documentation is necessary. 
- [ ] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### How has this code been tested

### Special notes for your reviewer

2022-03-29 11:01 UTC, wonderflow approved these changes

2022-03-29 11:21 UTC, FogDong reviewed
Great, thanks for the contribution!

Please also update the examples here: https://github.com/oam-dev/kubevela/blob/master/docs/examples/core-definitions/trait/storage.yaml

2022-03-29 11:35 UTC, FogDong requested changes
After changing `mountToEnv` to the array, the users who use the former version will be affected. 

In fact, we need to have definition revisions first to solve this problem.🤔

2022-03-29 12:23 UTC, ZhongsJie96 commented
> Great, thanks for the contribution!
> 
> Please also update the examples here: https://github.com/oam-dev/kubevela/blob/master/docs/examples/core-definitions/trait/storage.yaml

2022-03-29 12:24 UTC, ZhongsJie96 commented
> Great, thanks for the contribution!
> 
> Please also update the examples here: https://github.com/oam-dev/kubevela/blob/master/docs/examples/core-definitions/trait/storage.yaml

ok，I will add it

2022-03-29 12:43 UTC, ZhongsJie96 commented
> After changing `mountToEnv` to the array, the users who use the former version will be affected.
> 
> In fact, we need to have definition revisions first to solve this problem.🤔

As you said, this feature will affect the users who used it before. What should I do to define the revision? At the same time, I think it is a reasonable feature to support some special needs. Sorry, I accidentally closed this pr.

2022-03-30 02:32 UTC, Somefive commented
I think you can have two ways to keep compatibility. The first one is to rename this trait to a new trait such as `storages` or `multi-storage`. The second one is try to move the multi-settings in the propose changes in another field. You can see `container-image`, `env`, or `command` traits. /cc @FogDong

2022-04-08 08:00 UTC, anselmhou commented
Looking for this PR to be merge.  I have a use case where I have Kubernetes secrete that are defined externally with multiple key and value pairs, and those value pairs to the application as environment variables.

I can work around with `service-bindings` but since it is marked as deprecated so wishing to move to storage traits.  But in order to do and without the support of multiple `mountToEnv` it seems a blocker to me.  I cannot use a different name since it references the same secret in Kubernetes.

So thank you for the contribution and looking forward to this release and hoping to see it in the near future release of the project.

2022-04-08 10:03 UTC, FogDong commented
> Looking for this PR to be merge. I have a use case where I have Kubernetes secrete that are defined externally with multiple key and value pairs, and those value pairs to the application as environment variables.
> 
> I can work around with `service-bindings` but since it is marked as deprecated so wishing to move to storage traits. But in order to do and without the support of multiple `mountToEnv` it seems a blocker to me. I cannot use a different name since it references the same secret in Kubernetes.
> 
> So thank you for the contribution and looking forward to this release and hoping to see it in the near future release of the project.

Since definition revision is a large and complex feature, maybe we can add `mountToEnvs` first to support array in this definition. 
WDYT? /cc @ZhongsJie96

2022-04-14 08:15 UTC, closed without merging