Feat: allow select resource by resource type for gc policy
oam-dev/kubevela pull request #3598
Opened 2022-04-07 09:05 UTC by JooKS-me

Signed-off-by: zhukunshuai <jookunshuai@gmail.com>

### Description of your changes

About #3395

2022-04-11 12:26 UTC, Somefive commented
Great work! It is a bit ambiguous to use `resourceType`. It is like `Deployment` or `Service`. How about `OAMRourceType`?

2022-04-11 12:54 UTC, JooKS-me commented
> Great work! It is a bit ambiguous to use `resourceType`. It is like `Deployment` or `Service`. How about `OAMRourceType`?

Get it.

2022-04-12 06:13 UTC, wonderflow commented on apis/core.oam.dev/v1alpha1/garbagecollect_types.go
> +// if both traitTypes, resourceTypes and componentTypes are specified, combination logic is OR
```suggestion
// if both traitTypes, oamTypes and componentTypes are specified, combination logic is OR
```

2022-04-12 06:13 UTC, wonderflow commented on apis/core.oam.dev/v1alpha1/garbagecollect_types.go
> +	OAMResourceTypes []string `json:"OAMResourceTypes"`
```suggestion
	OAMResourceTypes []string `json:"oamTypes"`
```

2022-04-12 06:14 UTC, wonderflow commented on docs/examples/app-with-policy/gc-policy/persist-resources.md
> +              resourceTypes:
```suggestion
              oamTypes:
```

2022-04-12 06:15 UTC, wonderflow commented on docs/examples/app-with-policy/gc-policy/persist-resources.md
> +              resourceTypes:
```suggestion
              oamTypes:
```

2022-04-12 06:15 UTC, wonderflow requested changes
please align the example doc, annotation and code.

2022-04-12 06:53 UTC, JooKS-me commented
> please align the example doc, annotation and code.

ok

2022-04-12 10:51 UTC, merged