support raw CRD for APPFILE
oam-dev/kubevela pull request #573
Opened 2020-11-11 10:26 UTC by wonderflow

fix #565

2020-11-11 18:08 UTC, resouer commented
/close as this doesn't make sense to me at all ...

2020-11-12 02:28 UTC, wonderflow commented
@resouer  Changed the way

2020-11-12 02:32 UTC, resouer requested changes
This is totally wrong.

2020-11-12 02:52 UTC, resouer approved these changes

2020-11-12 03:08 UTC, merged